version: "3"
services:
  front-facemash:
    depends_on:
      - back-facemash
    build:
      context: .
      dockerfile: ./local-docker/local-front-facemash.Dockerfile
    restart: always
    volumes:
      - "../front-facemash:/front-facemash"
    ports:
      - "3101:3000"
  back-facemash:
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: ./local-docker/local-back-facemash.Dockerfile
    restart: always
    volumes:
      - "../back-facemash:/back-facemash"
    ports:
      - "3100:3000"
  mongodb:
    build:
      context: .
      dockerfile: ./local-docker/local-mongo-facemash.Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 37017:27017
    volumes:
      - local_mongodb_data:/data/db

volumes:
  local_mongodb_data:
    driver: local
